### ISSUE TITLE
Feed is broken

### ISSUE THREAD

**Issue by tfausak** [vaibhavsagar/vaibhavsagar.github.io#1]
http://vaibhavsagar.com/atom.xml

> This page contains the following errors:
> error on line 28 at column 32: Input is not proper UTF-8, indicate encoding !
> Bytes: 0x01 0xC2 0x95 0xC2

**Comment by vaibhavsagar** [comment]
Thanks for pointing this out! I'm just using Hakyll's built-in feed generation, do you have any advice on how to fix this issue?

**Comment by tfausak** [comment]
Not of the top of my head, sorry. I'll poke around in https://github.com/vaibhavsagar/website when I get some time.

**Comment by vaibhavsagar** [comment]
I think it might be because of [this bit](https://github.com/vaibhavsagar/website/blob/d144d81fd678beabd676a981df5cd7bb3b514808/blog/i-haskell-a-git.md#L157) which is binary output, but that doesn't correspond to line 28 so I'm not sure what's going on there or what to do to fix it. Any suggestions are appreciated 😃.

**Comment by tfausak** [comment]
Oh yeah, that's definitely going to be the problem. I'm not sure why the XML error shows up in an unrelated place. Running it through the W3C's feed validator shows [the expected failure](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fvaibhavsagar.com%2Fatom.xml):

![image](https://user-images.githubusercontent.com/408753/30623951-5a8acc6a-9d80-11e7-8fc0-968882f3b634.png)

For what it's worth, [the HTML is invalid](https://validator.w3.org/nu/?doc=http%3A%2F%2Fvaibhavsagar.com%2Fblog%2F2017%2F08%2F13%2Fi-haskell-a-git%2F) too. Lots of errors like this:

> Forbidden code point U+0001.

The problem is that you've got non-Unicode characters in an ostensibly Unicode string. (Haskell's strings are Unicode, but they also allow (some?) invalid code points.) For showing the raw binary data in a blog post, I would either:

- Display it as a [hex dump](https://en.wikipedia.org/wiki/Hex_dump) rather than the raw bytes.
- Display it as an image.

**Comment by vaibhavsagar** [comment]
Cool, I used `xxd` to display a hex dump, but now the null bytes in the rest of the post are causing errors in both the XML and HTML validators. I think converting those to hex dumps as well would make my post harder to understand and I'd rather not do that. I generated this blog post straight from [this notebook](https://github.com/vaibhavsagar/notebooks/blob/3238b6656234174da2950835ccf401046e53cf27/git-from-scratch/IHaskellAGit.ipynb) and I'd like to make a change to that notebook instead of the generated Markdown, which makes generating an image not a great approach.

**Comment by tfausak** [comment]
You could try substituting the null bytes with something else. For example, [U+2400](http://www.fileformat.info/info/unicode/char/2400/index.htm) (&#x2400;) could stand in for U+0000. I think you could do that with `tr`, but I don't know how off the top of my head.

**Comment by vaibhavsagar** [comment]
Good call! I tried `sed -i 's/\x0//g' blog/i-haskell-a-git.md` and that seemed to work. Feed validator and HTML are both looking good now.
